lib/main.dart
pubspec.lock
pubspec.yaml

Added Device Preview package logic for easier emulation for windows users

Added Device Preview

---

lib/src/screens/login_screen.dart

- Log In button is present and correctly positioned.
- Button is clickable and responsive.
- The UI follows the provided UX design.

Added login button to login page

---

lib/src/screens/signup_screen.dart

implementation of sign up button (#132) and implementation of sign up input fields  (#131)

#131 and #132 done, sign up page implementation

---

lib/src/screens/login_screen.dart
lib/src/screens/signup_screen.dart

This commit has the following implementations:
1. Wallpaper was added to signup screen
2. "archivo black" font was implemented
3. Appbar implementation was succesful

This commit is for issue #127 (Sign up wallpaper and title)

---

lib/src/routes/app_router.dart
lib/src/screens/gettoknow_screen.dart
lib/src/screens/signup_screen.dart

This has the following implementations:
- Error handling in sign up page
- Input validation in sign up page
- Screen transition to a blank get to know screen upon successful account creation
Note:
Some changes made in the sign up screen file that were about user authentication had to be removed for the moment in order to complete the previously mentioned implementations.

Error Handling and Get to know Screen creation

---

lib/src/screens/login_screen.dart

Implemented a validation method as a function to verify each user input in the username and password fields on the Log In screen. This included checking special characters, invalid characters, length of the password (Note: the length of the password was determined to be a minimum of 8 characters), correct email domain, and format. After all of this is true, that means that each field is validated. It was decided that for this Milestone we would directly change the boolean of isLoggedIn variable to true. Later on, once the Data Base is set up, we will pass through another extra validation method to compare the users credentials to the stored ones.

Solved and closed tasks #122, #124 and #125.

---

lib/src/screens/login_screen.dart

- Ensured that signup and login enforce the same password validation rules.
- Updated both frontend and backend validation to reflect the correct rules.
- Tested that users can sign up and log in successfully with valid passwords.

standardized password validation across sign up and login

---

lib/src/routes/app_router.dart
lib/src/screens/chat_screen.dart
lib/src/screens/dms_screen.dart
lib/src/screens/gettoknow_screen.dart
lib/src/widgets.dart

implemented messages/chat screen

---

lib/src/screens/chat_screen.dart
lib/src/widgets.dart

-Highlighted the messages tab icon when active
-Adjusted active tab yellow to look brighter
-Ensured the active tab is non-clickable

messages screen (bottom navigation bar logic)

---

lib/src/screens/user_profile_screen.dart

Here is the final mockup for the userprofile.

final userprofile mockup

---

lib/src/routes/app_router.dart
lib/src/screens/FAQ_screen.dart
lib/src/screens/menu_screen.dart

FAQ Screen Implementation

---

lib/services/firebase_cloud_messaging.dart
pubspec.yaml

Firebase Cloud Message was implemented

fcm implemantation

---

lib/src/screens/search_screen.dart

Reverts uprm-inso4101-2024-2025-s2/semester-project--uprm-pet-adoption#367

Revert "Implement search screen layout"

---

lib/src/screens/search_screen.dart

While this update may appear similar to the "Implement layout" task, it specifically focuses on the header functionality. This includes the addition of the circular back button styled with the app's color palette and a black border, as well as implementing its navigation functionality to return the user to the Home screen.

Implement header Functionality

---

lib/analytics_service.dart
lib/src/screens/auth_screen.dart
lib/src/screens/home_screen.dart
lib/src/screens/login_screen.dart
lib/src/screens/signup_screen.dart

This has the following implementatons:
- Firebase Analytics implementation
- Analytics service file to handle events

Firebase Analytics Implementation

---

lib/services/auth_service.dart
pubspec.lock
pubspec.yaml

Google sign in is implemented, but can't be tested due to front end not being available.
This commit is for task #338

Google sign in backend

---

lib/src/routes/app_router.dart
lib/src/screens/menu_screen.dart
lib/src/screens/shelter_info_screen.dart

Implemented the Shelter Info Screen with a scrollable list of shelter cards. Each card opens a pop-up window displaying contact info. Pop-up includes map icon that redirects to the map screen when pressed.

Implementation Shelter Info Screen and Functionality

---

lib/src/screens/search_screen.dart

Here is the implementation of Search Screen

Implementation Search Screen

---

lib/src/screens/user_profile_screen.dart

This PR has the implementation of the users profie picture being able to be uploaded and changed. When the user has no profile picture, it will display a default one until the user changes it. To add a profile picture or change it, simply press the area where the profile picture is at and it will prompt you to choose an image from your device.

Integration of Supabase Storage in Profile Screen

---

lib/src/screens/menu_screen.dart

fix a bug in setting screen code

fix bug screen setting implementation 

---

android/app/src/main/AndroidManifest.xml
ios/Podfile
ios/Runner/AppDelegate.swift
pubspec.yaml

This pull request is for task #476 and ensures the following criteria:
1. Generate a Google Maps API key from the Google Cloud Console.
2. Enable Maps SDK for Android and Maps SDK for iOS.
3. Add google_maps_flutter to pubspec.yaml.
4. Configure AndroidManifest.xml with the API key.
5. Configure AppDelegate.swift or AppDelegate.m for iOS.

Configured Google Maps API Key for task #476

---

lib/src/screens/FAQ_screen.dart
lib/src/screens/chat_screen.dart
lib/src/screens/favorites_screen.dart
lib/src/screens/gettoknow_screen.dart
lib/src/screens/menu_screen.dart
lib/src/screens/petProfile_screen.dart
lib/src/screens/pet_tips_screen.dart
lib/src/screens/search_screen.dart
lib/src/screens/settings_screen.dart
lib/src/screens/shelter_info_screen.dart
lib/src/screens/user_profile_screen.dart

This pull request is for issue #466 which is meant to expand on the tracking events in Firebase Analytics

Firebase Analytics Expansion

---

lib/services/auth_service.dart
lib/src/screens/signup_screen.dart
lib/src/screens/user_profile_screen.dart

This is due to the fact that the original commit is not appearing in main after pull request. 
The original commit is 49d3a21

Re commit of task 412/ commit 49d3a21

---

lib/src/screens/petProfile_screen.dart

This pull request solves a minro bug from a code that was mistakenly not fixed from the merge conflict resolving of the pet picture pull request.

quick merge conflict fix from pet picture PR

---

lib/analytics_service.dart
lib/services/auth_service.dart
lib/src/screens/login_screen.dart
lib/src/screens/petProfile_screen.dart
lib/src/screens/signup_screen.dart
lib/src/screens/user_profile_screen.dart
lib/supabase/retrieval.dart
lib/supabase/upload.dart

This commit has all the changes specified within tasks #475 and #524 
The sign up function for the pets has been established. It contains all the relevant fields necessary for creating the pet in the system. 
Specifically:
'medicalDocument'
'petPicture'
'petAge'// contains one of 3 options (Puppy, Adult, Elderly)
'petBreed'// contains the breed of the pet either from the selection or option other
'petDescription'// description and details that user gives of the pet
'petName'// created pets name
'petOwner'// the user who registered this pet
'petShelter'// the shelter that registered this pet
'petTags'//specific tags chosen from the new pet profile screen
'createdAt' // Add a timestamp
Note: the medical Document is created with this String: 'fileName For medicalDocument'
This is due to the …

Commit for tasks 475, 524 petSignUp function and variables and functions follow camelCase

---

lib/src/screens/loading_screen.dart

Description:
Create a pet-themed loading animation (e.g., paw print loop, bone spinner, playful pet motion) to be used during screen transitions or data loading phases in the app.
Objective:
Provide a visually appealing and consistent loading screen that enhances the user experience and matches the theme of the application.
This commit follows the following criteria and was tested before this request: 
- The loading screen appears full-screen and works on both platforms.
- It shows reliably during all major loading scenarios.
- Integration does not interfere with UI flow or layout.

This commit is for tasks #498. Designed loading screen

---

lib/src/screens/loading_screen.dart
lib/src/screens/login_screen.dart
lib/src/screens/signup_screen.dart

**Description:**
Implement a loading screen using the designed animation to enhance user experience during data loading or navigation events.
**Task Breakdown:**
1. Add the loading animation to the project.
2. Build a reusable LoadingScreen widget.
3. Implement logic to display it during operations or view transitions.
4. Test for smooth integration on Android and iOS.
**This commit was tested under the following Acceptance Criteri**a:
1. The animation appears full-screen and works on both platforms.
2. It shows reliably during all major loading scenarios.
3. Integration does not interfere with UI flow or layout.

This commit is for task #499, implemented loading screen

---

lib/src/screens/pet_article.dart
lib/src/screens/pet_tips_screen.dart

In this pull request I include the visual enhancements of the pet tips screen  and the creation of the pet article screen.

Pet care tips screen

---

lib/src/screens/petProfile_screen.dart

Here is the Final tag selection implementation of the new pet profile.

Final Tags

---

lib/src/screens/pet_tips_screen.dart

This pull request includes the implementation described in task #211

Pet tips screen backend implementation

---

lib/analytics_service.dart
lib/services/auth_service.dart
lib/services/firebase_cloud_messaging.dart
lib/src/providers/match_logic.dart

Added documentation of backend files/implementations where needed, check logbook for further details

Backend Documentation

---

lib/src/screens/user_profile_screen.dart
pubspec.yaml
test/_screen_rendering_test.dart

Added code for the phone number field which limits the user input to only numbers.

Phone number field bug fix

---

lib/src/screens/pet_tips_screen.dart

Added save button to pet articles as described in issue #587

Added save button to pet articles
